In [30]:
import pandas as pd

In [31]:
groups = {
    'education_char':'DP02',
    'economic_char':'DP03',
    'housing_char':'DP04',
    'demo_char':'DP05'
}

for characteristic in groups:
    exec(f'{characteristic} = pd.read_csv("{characteristic}.csv", index_col="municipality")')
    
place_char = pd.concat([education_char,economic_char,housing_char,demo_char], axis=1)

In [32]:
yar_char = place_char.loc[['West Yarmouth', 'Yarmouth Port', 'South Yarmouth']]

In [33]:
yar_char.head()

,KEY_population_25_and_older,edu_high_school_and_higher_%,edu_bachelors_and_higher_%,KEY_pop_16_+,unemployment_rate_%,median_household_income,mean_household_income,families_below_poverty_level_%,people_below_poverty_level_%,KEY_total_housing_units,...,KEY_total_population,males-to-100females,median_age,demo_white_%,demo_black_aa_%,demo_american_indian_%,demo_asian_%,demo_native_islander%,demo_other_Race_%,demo_hispanic_latino_%
municipality,,,,,,,,,,,,,,,,,,,,,
West Yarmouth,4477,90.3,34.7,4928,2.7,61956,78616,6.0,6.7,5189,...,5741,80.9,48.8,86.3,6.0,0.9,6.2,1.2,4.4,5.1
Yarmouth Port,4404,97.5,53.0,4738,2.0,74737,99238,4.3,5.7,3278,...,5242,77.8,63.3,99.8,0.2,0.6,0.0,0.0,0.0,1.8
South Yarmouth,8793,95.1,28.8,9816,5.9,61088,76609,3.9,7.2,7771,...,11091,88.0,52.4,91.9,4.5,0.7,2.7,0.3,2.6,2.2

In [34]:
demo_char.columns

Index(['KEY_total_population', 'males-to-100females', 'median_age',
       'demo_white_%', 'demo_black_aa_%', 'demo_american_indian_%',
       'demo_asian_%', 'demo_native_islander%', 'demo_other_Race_%',
       'demo_hispanic_latino_%'],
      dtype='object')

In [35]:
# df[["A", "B"]].multiply(df["C"], axis="index")

yar_char[['edu_high_school_and_higher_%', 'edu_bachelors_and_higher_%']] = yar_char[['edu_high_school_and_higher_%', 'edu_bachelors_and_higher_%']].multiply(yar_char['KEY_population_25_and_older'], axis='index')

In [36]:
yar_char[['unemployment_rate_%', 'median_household_income',
       'mean_household_income', 'families_below_poverty_level_%',
       'people_below_poverty_level_%']] = yar_char[['unemployment_rate_%', 'median_household_income',
       'mean_household_income', 'families_below_poverty_level_%',
       'people_below_poverty_level_%']].multiply(yar_char['KEY_pop_16_+'], axis='index')

In [37]:
yar_char[['occupancy_%', '1-unit_detached_%',
       '1-unit_attached_%', '2-units_%', '3-4_units_%', '5-9_units_%',
       '10-19_units_%', '20+_units_%', 'mobile_home_%', 'boat_RV_van_%',
       'owner-occupied_%', 'renter-occupied_%']] = yar_char[['occupancy_%', '1-unit_detached_%',
       '1-unit_attached_%', '2-units_%', '3-4_units_%', '5-9_units_%',
       '10-19_units_%', '20+_units_%', 'mobile_home_%', 'boat_RV_van_%',
       'owner-occupied_%', 'renter-occupied_%']].multiply(yar_char['KEY_total_housing_units'], axis='index')

In [38]:
yar_char[['males-to-100females', 'median_age',
       'demo_white_%', 'demo_black_aa_%', 'demo_american_indian_%',
       'demo_asian_%', 'demo_native_islander%', 'demo_other_Race_%',
       'demo_hispanic_latino_%']] = yar_char[['males-to-100females', 'median_age',
       'demo_white_%', 'demo_black_aa_%', 'demo_american_indian_%',
       'demo_asian_%', 'demo_native_islander%', 'demo_other_Race_%',
       'demo_hispanic_latino_%']].multiply(yar_char['KEY_total_population'], axis='index')

In [39]:
yar_char.loc['Yarmouth'] = yar_char.loc[['West Yarmouth', 'Yarmouth Port', 'South Yarmouth']].sum()

In [40]:
yar_char[['edu_high_school_and_higher_%', 'edu_bachelors_and_higher_%']] = yar_char[['edu_high_school_and_higher_%', 'edu_bachelors_and_higher_%']].div(yar_char['KEY_population_25_and_older'], axis='index')

In [41]:
yar_char[['unemployment_rate_%', 'median_household_income',
       'mean_household_income', 'families_below_poverty_level_%',
       'people_below_poverty_level_%']] = yar_char[['unemployment_rate_%', 'median_household_income',
       'mean_household_income', 'families_below_poverty_level_%',
       'people_below_poverty_level_%']].div(yar_char['KEY_pop_16_+'], axis='index')

In [42]:
yar_char[['occupancy_%', '1-unit_detached_%',
       '1-unit_attached_%', '2-units_%', '3-4_units_%', '5-9_units_%',
       '10-19_units_%', '20+_units_%', 'mobile_home_%', 'boat_RV_van_%',
       'owner-occupied_%', 'renter-occupied_%']] = yar_char[['occupancy_%', '1-unit_detached_%',
       '1-unit_attached_%', '2-units_%', '3-4_units_%', '5-9_units_%',
       '10-19_units_%', '20+_units_%', 'mobile_home_%', 'boat_RV_van_%',
       'owner-occupied_%', 'renter-occupied_%']].div(yar_char['KEY_total_housing_units'], axis='index')

In [43]:
yar_char[['males-to-100females', 'median_age',
       'demo_white_%', 'demo_black_aa_%', 'demo_american_indian_%',
       'demo_asian_%', 'demo_native_islander%', 'demo_other_Race_%',
       'demo_hispanic_latino_%']] = yar_char[['males-to-100females', 'median_age',
       'demo_white_%', 'demo_black_aa_%', 'demo_american_indian_%',
       'demo_asian_%', 'demo_native_islander%', 'demo_other_Race_%',
       'demo_hispanic_latino_%']].div(yar_char['KEY_total_population'], axis='index')

In [44]:
yar_char

,KEY_population_25_and_older,edu_high_school_and_higher_%,edu_bachelors_and_higher_%,KEY_pop_16_+,unemployment_rate_%,median_household_income,mean_household_income,families_below_poverty_level_%,people_below_poverty_level_%,KEY_total_housing_units,...,KEY_total_population,males-to-100females,median_age,demo_white_%,demo_black_aa_%,demo_american_indian_%,demo_asian_%,demo_native_islander%,demo_other_Race_%,demo_hispanic_latino_%
municipality,,,,,,,,,,,,,,,,,,,,,
West Yarmouth,4477.0,90.300000,34.700000,4928.0,2.70000,61956.000000,78616.000000,6.000000,6.700000,5189.0,...,5741.0,80.9000,48.800000,86.300000,6.000000,0.900000,6.200000,1.20000,4.400000,5.100000
Yarmouth Port,4404.0,97.500000,53.000000,4738.0,2.00000,74737.000000,99238.000000,4.300000,5.700000,3278.0,...,5242.0,77.8000,63.300000,99.800000,0.200000,0.600000,0.000000,0.00000,0.000000,1.800000
South Yarmouth,8793.0,95.100000,28.800000,9816.0,5.90000,61088.000000,76609.000000,3.900000,7.200000,7771.0,...,11091.0,88.0000,52.400000,91.900000,4.500000,0.700000,2.700000,0.30000,2.600000,2.200000
Yarmouth,17674.0,94.482143,36.324675,19482.0,4.14208,64626.982959,82620.020326,4.528478,6.708726,16238.0,...,22074.0,83.7312,54.052179,92.319598,3.868982,0.728269,2.969099,0.46283,2.450711,2.859242

In [45]:
# For saving files

# yar_char.to_csv('yarmouth_correction.csv', index=True)